// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package dependencies

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDependency = `-- name: CreateDependency :one
INSERT INTO sprint_management.work_item_dependencies (
    source_id,
    target_id,
    dependency_type,
    created_by
) VALUES (
    $1, $2, $3, $4
) RETURNING id, source_id, target_id, dependency_type, created_at, created_by
`

type CreateDependencyParams struct {
	SourceID       pgtype.UUID                    `json:"source_id"`
	TargetID       pgtype.UUID                    `json:"target_id"`
	DependencyType SprintManagementDependencyType `json:"dependency_type"`
	CreatedBy      pgtype.UUID                    `json:"created_by"`
}

func (q *Queries) CreateDependency(ctx context.Context, arg CreateDependencyParams) (SprintManagementWorkItemDependency, error) {
	row := q.db.QueryRow(ctx, createDependency,
		arg.SourceID,
		arg.TargetID,
		arg.DependencyType,
		arg.CreatedBy,
	)
	var i SprintManagementWorkItemDependency
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.DependencyType,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteDependenciesByWorkItemID = `-- name: DeleteDependenciesByWorkItemID :exec
DELETE FROM sprint_management.work_item_dependencies
WHERE source_id = $1 OR target_id = $1
`

func (q *Queries) DeleteDependenciesByWorkItemID(ctx context.Context, sourceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDependenciesByWorkItemID, sourceID)
	return err
}

const deleteDependency = `-- name: DeleteDependency :exec
DELETE FROM sprint_management.work_item_dependencies
WHERE id = $1
`

func (q *Queries) DeleteDependency(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDependency, id)
	return err
}

const dependencyExists = `-- name: DependencyExists :one
SELECT EXISTS(
    SELECT 1 FROM sprint_management.work_item_dependencies
    WHERE source_id = $1 
    AND target_id = $2 
    AND dependency_type = $3
) as exists
`

type DependencyExistsParams struct {
	SourceID       pgtype.UUID                    `json:"source_id"`
	TargetID       pgtype.UUID                    `json:"target_id"`
	DependencyType SprintManagementDependencyType `json:"dependency_type"`
}

func (q *Queries) DependencyExists(ctx context.Context, arg DependencyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, dependencyExists, arg.SourceID, arg.TargetID, arg.DependencyType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllDependenciesForWorkItem = `-- name: GetAllDependenciesForWorkItem :many
SELECT id, source_id, target_id, dependency_type, created_at, created_by FROM sprint_management.work_item_dependencies
WHERE source_id = $1 OR target_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllDependenciesForWorkItem(ctx context.Context, sourceID pgtype.UUID) ([]SprintManagementWorkItemDependency, error) {
	rows, err := q.db.Query(ctx, getAllDependenciesForWorkItem, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementWorkItemDependency{}
	for rows.Next() {
		var i SprintManagementWorkItemDependency
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.DependencyType,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockingDependencies = `-- name: GetBlockingDependencies :many
SELECT d.id, d.source_id, d.target_id, d.dependency_type, d.created_at, d.created_by, wi.status as source_status
FROM sprint_management.work_item_dependencies d
JOIN sprint_management.work_items wi ON d.source_id = wi.id
WHERE d.target_id = $1 
AND d.dependency_type = 'blocks'
AND wi.status != 'done' 
AND wi.deleted_at IS NULL
ORDER BY d.created_at DESC
`

type GetBlockingDependenciesRow struct {
	ID             pgtype.UUID                    `json:"id"`
	SourceID       pgtype.UUID                    `json:"source_id"`
	TargetID       pgtype.UUID                    `json:"target_id"`
	DependencyType SprintManagementDependencyType `json:"dependency_type"`
	CreatedAt      pgtype.Timestamptz             `json:"created_at"`
	CreatedBy      pgtype.UUID                    `json:"created_by"`
	SourceStatus   SprintManagementWorkItemStatus `json:"source_status"`
}

func (q *Queries) GetBlockingDependencies(ctx context.Context, targetID pgtype.UUID) ([]GetBlockingDependenciesRow, error) {
	rows, err := q.db.Query(ctx, getBlockingDependencies, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockingDependenciesRow{}
	for rows.Next() {
		var i GetBlockingDependenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.DependencyType,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.SourceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependenciesBySourceID = `-- name: GetDependenciesBySourceID :many
SELECT id, source_id, target_id, dependency_type, created_at, created_by FROM sprint_management.work_item_dependencies
WHERE source_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDependenciesBySourceID(ctx context.Context, sourceID pgtype.UUID) ([]SprintManagementWorkItemDependency, error) {
	rows, err := q.db.Query(ctx, getDependenciesBySourceID, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementWorkItemDependency{}
	for rows.Next() {
		var i SprintManagementWorkItemDependency
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.DependencyType,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependenciesByTargetID = `-- name: GetDependenciesByTargetID :many
SELECT id, source_id, target_id, dependency_type, created_at, created_by FROM sprint_management.work_item_dependencies
WHERE target_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDependenciesByTargetID(ctx context.Context, targetID pgtype.UUID) ([]SprintManagementWorkItemDependency, error) {
	rows, err := q.db.Query(ctx, getDependenciesByTargetID, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementWorkItemDependency{}
	for rows.Next() {
		var i SprintManagementWorkItemDependency
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.DependencyType,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependencyByID = `-- name: GetDependencyByID :one
SELECT id, source_id, target_id, dependency_type, created_at, created_by FROM sprint_management.work_item_dependencies
WHERE id = $1
`

func (q *Queries) GetDependencyByID(ctx context.Context, id pgtype.UUID) (SprintManagementWorkItemDependency, error) {
	row := q.db.QueryRow(ctx, getDependencyByID, id)
	var i SprintManagementWorkItemDependency
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.DependencyType,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const hasBlockingDependencies = `-- name: HasBlockingDependencies :one
SELECT EXISTS(
    SELECT 1 FROM sprint_management.work_item_dependencies
    WHERE target_id = $1 
    AND dependency_type = 'blocks'
    AND source_id IN (
        SELECT id FROM sprint_management.work_items
        WHERE status != 'done' AND deleted_at IS NULL
    )
) as has_blocking
`

func (q *Queries) HasBlockingDependencies(ctx context.Context, targetID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasBlockingDependencies, targetID)
	var has_blocking bool
	err := row.Scan(&has_blocking)
	return has_blocking, err
}
