// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dependencies

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDependency(ctx context.Context, arg CreateDependencyParams) (SprintManagementWorkItemDependency, error)
	DeleteDependenciesByWorkItemID(ctx context.Context, sourceID pgtype.UUID) error
	DeleteDependency(ctx context.Context, id pgtype.UUID) error
	DependencyExists(ctx context.Context, arg DependencyExistsParams) (bool, error)
	GetAllDependenciesForWorkItem(ctx context.Context, sourceID pgtype.UUID) ([]SprintManagementWorkItemDependency, error)
	GetBlockingDependencies(ctx context.Context, targetID pgtype.UUID) ([]GetBlockingDependenciesRow, error)
	GetDependenciesBySourceID(ctx context.Context, sourceID pgtype.UUID) ([]SprintManagementWorkItemDependency, error)
	GetDependenciesByTargetID(ctx context.Context, targetID pgtype.UUID) ([]SprintManagementWorkItemDependency, error)
	GetDependencyByID(ctx context.Context, id pgtype.UUID) (SprintManagementWorkItemDependency, error)
	HasBlockingDependencies(ctx context.Context, targetID pgtype.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
