// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package comments

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityLogsByEntity = `-- name: CountActivityLogsByEntity :one
SELECT COUNT(*) FROM sprint_management.activity_logs
WHERE entity_type = $1 AND entity_id = $2
`

type CountActivityLogsByEntityParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) CountActivityLogsByEntity(ctx context.Context, arg CountActivityLogsByEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogsByEntity, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityLogsByUser = `-- name: CountActivityLogsByUser :one
SELECT COUNT(*) FROM sprint_management.activity_logs
WHERE user_id = $1
`

func (q *Queries) CountActivityLogsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO sprint_management.activity_logs (
    entity_type,
    entity_id,
    action,
    user_id,
    changes,
    trace_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, entity_type, entity_id, action, user_id, changes, trace_id, created_at
`

type CreateActivityLogParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Action     string      `json:"action"`
	UserID     pgtype.UUID `json:"user_id"`
	Changes    []byte      `json:"changes"`
	TraceID    pgtype.UUID `json:"trace_id"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (SprintManagementActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.UserID,
		arg.Changes,
		arg.TraceID,
	)
	var i SprintManagementActivityLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.UserID,
		&i.Changes,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const getActivityLogByID = `-- name: GetActivityLogByID :one
SELECT id, entity_type, entity_id, action, user_id, changes, trace_id, created_at FROM sprint_management.activity_logs
WHERE id = $1
`

func (q *Queries) GetActivityLogByID(ctx context.Context, id pgtype.UUID) (SprintManagementActivityLog, error) {
	row := q.db.QueryRow(ctx, getActivityLogByID, id)
	var i SprintManagementActivityLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.UserID,
		&i.Changes,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityLogsByAction = `-- name: ListActivityLogsByAction :many
SELECT id, entity_type, entity_id, action, user_id, changes, trace_id, created_at FROM sprint_management.activity_logs
WHERE action = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogsByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListActivityLogsByAction(ctx context.Context, arg ListActivityLogsByActionParams) ([]SprintManagementActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementActivityLog{}
	for rows.Next() {
		var i SprintManagementActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.UserID,
			&i.Changes,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogsByEntity = `-- name: ListActivityLogsByEntity :many
SELECT id, entity_type, entity_id, action, user_id, changes, trace_id, created_at FROM sprint_management.activity_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListActivityLogsByEntityParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListActivityLogsByEntity(ctx context.Context, arg ListActivityLogsByEntityParams) ([]SprintManagementActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementActivityLog{}
	for rows.Next() {
		var i SprintManagementActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.UserID,
			&i.Changes,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogsByTraceID = `-- name: ListActivityLogsByTraceID :many
SELECT id, entity_type, entity_id, action, user_id, changes, trace_id, created_at FROM sprint_management.activity_logs
WHERE trace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListActivityLogsByTraceID(ctx context.Context, traceID pgtype.UUID) ([]SprintManagementActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByTraceID, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementActivityLog{}
	for rows.Next() {
		var i SprintManagementActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.UserID,
			&i.Changes,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogsByUser = `-- name: ListActivityLogsByUser :many
SELECT id, entity_type, entity_id, action, user_id, changes, trace_id, created_at FROM sprint_management.activity_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]SprintManagementActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementActivityLog{}
	for rows.Next() {
		var i SprintManagementActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.UserID,
			&i.Changes,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivityLogs = `-- name: ListRecentActivityLogs :many
SELECT id, entity_type, entity_id, action, user_id, changes, trace_id, created_at FROM sprint_management.activity_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentActivityLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecentActivityLogs(ctx context.Context, arg ListRecentActivityLogsParams) ([]SprintManagementActivityLog, error) {
	rows, err := q.db.Query(ctx, listRecentActivityLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementActivityLog{}
	for rows.Next() {
		var i SprintManagementActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.UserID,
			&i.Changes,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
