// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package comments

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByWorkItem = `-- name: CountCommentsByWorkItem :one
SELECT COUNT(*) FROM sprint_management.comments
WHERE work_item_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCommentsByWorkItem(ctx context.Context, workItemID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByWorkItem, workItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO sprint_management.comments (
    work_item_id,
    author_id,
    content
) VALUES (
    $1, $2, $3
) RETURNING id, work_item_id, author_id, content, created_at, updated_at, deleted_at, deleted_by
`

type CreateCommentParams struct {
	WorkItemID pgtype.UUID `json:"work_item_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Content    string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (SprintManagementComment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.WorkItemID, arg.AuthorID, arg.Content)
	var i SprintManagementComment
	err := row.Scan(
		&i.ID,
		&i.WorkItemID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, work_item_id, author_id, content, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.comments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (SprintManagementComment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i SprintManagementComment
	err := row.Scan(
		&i.ID,
		&i.WorkItemID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getCommentByIDIncludingDeleted = `-- name: GetCommentByIDIncludingDeleted :one
SELECT id, work_item_id, author_id, content, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.comments
WHERE id = $1
`

func (q *Queries) GetCommentByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (SprintManagementComment, error) {
	row := q.db.QueryRow(ctx, getCommentByIDIncludingDeleted, id)
	var i SprintManagementComment
	err := row.Scan(
		&i.ID,
		&i.WorkItemID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listCommentsByAuthor = `-- name: ListCommentsByAuthor :many
SELECT id, work_item_id, author_id, content, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.comments
WHERE author_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCommentsByAuthorParams struct {
	AuthorID pgtype.UUID `json:"author_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListCommentsByAuthor(ctx context.Context, arg ListCommentsByAuthorParams) ([]SprintManagementComment, error) {
	rows, err := q.db.Query(ctx, listCommentsByAuthor, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementComment{}
	for rows.Next() {
		var i SprintManagementComment
		if err := rows.Scan(
			&i.ID,
			&i.WorkItemID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByWorkItem = `-- name: ListCommentsByWorkItem :many
SELECT id, work_item_id, author_id, content, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.comments
WHERE work_item_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByWorkItem(ctx context.Context, workItemID pgtype.UUID) ([]SprintManagementComment, error) {
	rows, err := q.db.Query(ctx, listCommentsByWorkItem, workItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementComment{}
	for rows.Next() {
		var i SprintManagementComment
		if err := rows.Scan(
			&i.ID,
			&i.WorkItemID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoftDeletedComments = `-- name: ListSoftDeletedComments :many
SELECT id, work_item_id, author_id, content, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.comments
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
LIMIT $1 OFFSET $2
`

type ListSoftDeletedCommentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSoftDeletedComments(ctx context.Context, arg ListSoftDeletedCommentsParams) ([]SprintManagementComment, error) {
	rows, err := q.db.Query(ctx, listSoftDeletedComments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementComment{}
	for rows.Next() {
		var i SprintManagementComment
		if err := rows.Scan(
			&i.ID,
			&i.WorkItemID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentlyDeleteComment = `-- name: PermanentlyDeleteComment :exec
DELETE FROM sprint_management.comments
WHERE id = $1
`

func (q *Queries) PermanentlyDeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, permanentlyDeleteComment, id)
	return err
}

const restoreComment = `-- name: RestoreComment :exec
UPDATE sprint_management.comments
SET
    deleted_at = NULL,
    deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreComment, id)
	return err
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE sprint_management.comments
SET
    deleted_at = NOW() AT TIME ZONE 'UTC',
    deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteCommentParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) error {
	_, err := q.db.Exec(ctx, softDeleteComment, arg.ID, arg.DeletedBy)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE sprint_management.comments
SET
    content = $2,
    updated_at = NOW() AT TIME ZONE 'UTC'
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, work_item_id, author_id, content, created_at, updated_at, deleted_at, deleted_by
`

type UpdateCommentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (SprintManagementComment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i SprintManagementComment
	err := row.Scan(
		&i.ID,
		&i.WorkItemID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
