// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package comments

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActivityLogsByEntity(ctx context.Context, arg CountActivityLogsByEntityParams) (int64, error)
	CountActivityLogsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountCommentsByWorkItem(ctx context.Context, workItemID pgtype.UUID) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (SprintManagementActivityLog, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (SprintManagementComment, error)
	GetActivityLogByID(ctx context.Context, id pgtype.UUID) (SprintManagementActivityLog, error)
	GetCommentByID(ctx context.Context, id pgtype.UUID) (SprintManagementComment, error)
	GetCommentByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (SprintManagementComment, error)
	ListActivityLogsByAction(ctx context.Context, arg ListActivityLogsByActionParams) ([]SprintManagementActivityLog, error)
	ListActivityLogsByEntity(ctx context.Context, arg ListActivityLogsByEntityParams) ([]SprintManagementActivityLog, error)
	ListActivityLogsByTraceID(ctx context.Context, traceID pgtype.UUID) ([]SprintManagementActivityLog, error)
	ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]SprintManagementActivityLog, error)
	ListCommentsByAuthor(ctx context.Context, arg ListCommentsByAuthorParams) ([]SprintManagementComment, error)
	ListCommentsByWorkItem(ctx context.Context, workItemID pgtype.UUID) ([]SprintManagementComment, error)
	ListRecentActivityLogs(ctx context.Context, arg ListRecentActivityLogsParams) ([]SprintManagementActivityLog, error)
	ListSoftDeletedComments(ctx context.Context, arg ListSoftDeletedCommentsParams) ([]SprintManagementComment, error)
	PermanentlyDeleteComment(ctx context.Context, id pgtype.UUID) error
	RestoreComment(ctx context.Context, id pgtype.UUID) error
	SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (SprintManagementComment, error)
}

var _ Querier = (*Queries)(nil)
