version: '3.9'

services:
  keycloak:
    container_name: ttrpg-keycloak
    image: keycloak/keycloak:26.5
    command: start
    environment:
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/ttrpg-pg

      # @see ~/ttrpg/ttrpg-api/deploy/postgres/postgres/keycloak.init.sql
      # defines user/pass & schema
      KC_DB_SCHEMA: keycloak_schema
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak_user}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-keycloak_password}

    ports:
      - 8080:8080
      - 9000:9000
    restart: always
    depends_on:
      - postgresql
