"""0001_init.

Revision ID: f9db5edc1a2b
Revises: 
Create Date: 2025-09-14 21:16:48.162053

"""
from typing import Sequence
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9db5edc1a2b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Database migration: upgrade."""
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_short', sa.String(), nullable=False),
    sa.Column('dnd_version', sa.String(), nullable=False),
    sa.Column('dnd_version_year', sa.Integer(), nullable=False),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source')),
    sa.UniqueConstraint('name', 'dnd_version', 'dnd_version_year', name='uq_source_name_version_year'),
    sa.UniqueConstraint('name', name=op.f('uq_source_name')),
    sa.UniqueConstraint('name_short', 'dnd_version', 'dnd_version_year', name='uq_source_name_short_version_year'),
    sa.UniqueConstraint('name_short', name=op.f('uq_source_name_short')),
    schema='dnd'
    )
    op.create_index(op.f('ix_dnd_source_id'), 'source', ['id'], unique=False, schema='dnd')
    op.create_index(op.f('ix_dnd_source_updated_at'), 'source', ['updated_at'], unique=False, schema='dnd')
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    schema='dnd'
    )
    op.create_index(op.f('ix_dnd_user_id'), 'user', ['id'], unique=False, schema='dnd')
    op.create_table('spell',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('CANTRIP', 'FIRST', 'SECOND', 'THIRD', 'FOURTH', 'FIFTH', 'SIXTH', 'SEVENTH', 'EIGHTH', 'NINTH', name='spelllevelenum', schema='dnd'), nullable=False),
    sa.Column('school', sa.Enum('ABJURATION', 'ALTERATION', 'CONJURATION', 'DIVINATION', 'ENCHANTMENT', 'EVOCATION', 'TRANSMUTATION', 'ILLUSION', 'INVOCATION', 'NECROMANCY', name='spellschoolenum', schema='dnd'), nullable=False),
    sa.Column('is_ritual', sa.Boolean(), nullable=False),
    sa.Column('casting_time', sa.String(), nullable=False),
    sa.Column('range', sa.String(), nullable=False),
    sa.Column('has_verbal_component', sa.Boolean(), nullable=False),
    sa.Column('has_somatic_component', sa.Boolean(), nullable=False),
    sa.Column('has_material_component', sa.Boolean(), nullable=False),
    sa.Column('materials', sa.String(), nullable=True),
    sa.Column('has_spell_cost', sa.Boolean(), nullable=False),
    sa.Column('are_materials_consumed', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('is_concentration', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('has_saving_throw', sa.Boolean(), nullable=False),
    sa.Column('difficulty_class_saving_throw_override', sa.Integer(), nullable=True),
    sa.Column('damage_type', sa.String(), nullable=True),
    sa.Column('at_higher_levels', sa.String(), nullable=True),
    sa.Column('difficulty_class_saving_throw', sa.String(), nullable=True),
    sa.Column('difficulty_class_type', sa.String(), nullable=True),
    sa.Column('stat_blocks', sa.JSON(), nullable=True),
    sa.Column('is_homebrew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['dnd.source.id'], name=op.f('fk_spell_source_id_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spell')),
    sa.UniqueConstraint('source_id', 'name', name='ux_spell_source_name'),
    schema='dnd'
    )
    op.create_index(op.f('ix_dnd_spell_id'), 'spell', ['id'], unique=False, schema='dnd')
    op.create_index(op.f('ix_dnd_spell_updated_at'), 'spell', ['updated_at'], unique=False, schema='dnd')
    # ### end Alembic commands ###

    post_upgrade()


def downgrade() -> None:
    """Database migration: downgrade."""
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dnd_spell_updated_at'), table_name='spell', schema='dnd')
    op.drop_index(op.f('ix_dnd_spell_id'), table_name='spell', schema='dnd')
    op.drop_table('spell', schema='dnd')
    op.drop_index(op.f('ix_dnd_user_id'), table_name='user', schema='dnd')
    op.drop_table('user', schema='dnd')
    op.drop_index(op.f('ix_dnd_source_updated_at'), table_name='source', schema='dnd')
    op.drop_index(op.f('ix_dnd_source_id'), table_name='source', schema='dnd')
    op.drop_table('source', schema='dnd')
    # ### end Alembic commands ###

    post_downgrade()


def pre_upgrade() -> None:
    """Processing before upgrading the schema."""
    pass


def post_upgrade() -> None:
    """Processing after upgrading the schema."""
    pass


def pre_downgrade() -> None:
    """Processing before downgrading the schema."""
    pass


def post_downgrade() -> None:
    """Processing after downgrading the schema."""
    pass
