// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workitems

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Count filtered results without search
	CountFilteredWorkItems(ctx context.Context, arg CountFilteredWorkItemsParams) (int64, error)
	// Count total search results for pagination
	CountSearchResults(ctx context.Context, plaintoTsquery string) (int64, error)
	CountWorkItemsBySprint(ctx context.Context, sprintID pgtype.UUID) (int64, error)
	CountWorkItemsByStatus(ctx context.Context, status SprintManagementWorkItemStatus) (int64, error)
	CreateWorkItem(ctx context.Context, arg CreateWorkItemParams) (SprintManagementWorkItem, error)
	// Advanced filtering without search text
	FilterWorkItems(ctx context.Context, arg FilterWorkItemsParams) ([]SprintManagementWorkItem, error)
	GetWorkItemByID(ctx context.Context, id pgtype.UUID) (GetWorkItemByIDRow, error)
	GetWorkItemByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (SprintManagementWorkItem, error)
	HasChildren(ctx context.Context, parentID pgtype.UUID) (bool, error)
	HasDependencies(ctx context.Context, sourceID pgtype.UUID) (bool, error)
	ListSoftDeletedWorkItems(ctx context.Context, arg ListSoftDeletedWorkItemsParams) ([]SprintManagementWorkItem, error)
	ListWorkItems(ctx context.Context, arg ListWorkItemsParams) ([]ListWorkItemsRow, error)
	ListWorkItemsByAssignee(ctx context.Context, arg ListWorkItemsByAssigneeParams) ([]SprintManagementWorkItem, error)
	ListWorkItemsByParent(ctx context.Context, parentID pgtype.UUID) ([]SprintManagementWorkItem, error)
	ListWorkItemsBySprint(ctx context.Context, sprintID pgtype.UUID) ([]ListWorkItemsBySprintRow, error)
	ListWorkItemsByStatus(ctx context.Context, arg ListWorkItemsByStatusParams) ([]SprintManagementWorkItem, error)
	ListWorkItemsByType(ctx context.Context, arg ListWorkItemsByTypeParams) ([]SprintManagementWorkItem, error)
	PermanentlyDeleteWorkItem(ctx context.Context, id pgtype.UUID) error
	RestoreWorkItem(ctx context.Context, id pgtype.UUID) error
	// Search queries for work items with full-text search support
	SearchWorkItems(ctx context.Context, arg SearchWorkItemsParams) ([]SearchWorkItemsRow, error)
	// Boolean search with AND/OR operators using websearch_to_tsquery
	SearchWorkItemsBoolean(ctx context.Context, arg SearchWorkItemsBooleanParams) ([]SearchWorkItemsBooleanRow, error)
	// Field-specific search supporting title, description, or both
	SearchWorkItemsByField(ctx context.Context, arg SearchWorkItemsByFieldParams) ([]SearchWorkItemsByFieldRow, error)
	SearchWorkItemsWithFilters(ctx context.Context, arg SearchWorkItemsWithFiltersParams) ([]SearchWorkItemsWithFiltersRow, error)
	SoftDeleteWorkItem(ctx context.Context, arg SoftDeleteWorkItemParams) error
	SumCompletedStoryPointsBySprint(ctx context.Context, sprintID pgtype.UUID) (interface{}, error)
	SumStoryPointsBySprint(ctx context.Context, sprintID pgtype.UUID) (interface{}, error)
	UpdateWorkItem(ctx context.Context, arg UpdateWorkItemParams) (SprintManagementWorkItem, error)
}

var _ Querier = (*Queries)(nil)
