// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package workitems

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilteredWorkItems = `-- name: CountFilteredWorkItems :one
SELECT COUNT(*) FROM sprint_management.work_items w
WHERE 
    deleted_at IS NULL
    AND ($1::sprint_management.work_item_type IS NULL OR w.type = $1)
    AND ($2::sprint_management.work_item_status IS NULL OR w.status = $2)
    AND ($3::sprint_management.priority_level IS NULL OR w.priority = $3)
    AND ($4::uuid IS NULL OR w.assignee_id = $4)
    AND ($5::uuid IS NULL OR w.sprint_id = $5)
    AND ($6::uuid IS NULL OR w.reporter_id = $6)
    AND ($7::uuid IS NULL OR w.parent_id = $7)
`

type CountFilteredWorkItemsParams struct {
	Column1 SprintManagementWorkItemType   `json:"column_1"`
	Column2 SprintManagementWorkItemStatus `json:"column_2"`
	Column3 SprintManagementPriorityLevel  `json:"column_3"`
	Column4 pgtype.UUID                    `json:"column_4"`
	Column5 pgtype.UUID                    `json:"column_5"`
	Column6 pgtype.UUID                    `json:"column_6"`
	Column7 pgtype.UUID                    `json:"column_7"`
}

// Count filtered results without search
func (q *Queries) CountFilteredWorkItems(ctx context.Context, arg CountFilteredWorkItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredWorkItems,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchResults = `-- name: CountSearchResults :one
SELECT COUNT(*) FROM sprint_management.work_items w
WHERE 
    deleted_at IS NULL
    AND to_tsvector('english', w.title || ' ' || COALESCE(w.description, '')) @@ plainto_tsquery('english', $1)
`

// Count total search results for pagination
func (q *Queries) CountSearchResults(ctx context.Context, plaintoTsquery string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchResults, plaintoTsquery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filterWorkItems = `-- name: FilterWorkItems :many
SELECT id, type, title, description, status, priority, story_points, assignee_id, reporter_id, parent_id, sprint_id, created_at, updated_at, deleted_at, deleted_by, project_id, ticket_number FROM sprint_management.work_items w
WHERE 
    deleted_at IS NULL
    AND ($1::sprint_management.work_item_type IS NULL OR w.type = $1)
    AND ($2::sprint_management.work_item_status IS NULL OR w.status = $2)
    AND ($3::sprint_management.priority_level IS NULL OR w.priority = $3)
    AND ($4::uuid IS NULL OR w.assignee_id = $4)
    AND ($5::uuid IS NULL OR w.sprint_id = $5)
    AND ($6::uuid IS NULL OR w.reporter_id = $6)
    AND ($7::uuid IS NULL OR w.parent_id = $7)
ORDER BY created_at DESC, id
LIMIT $8 OFFSET $9
`

type FilterWorkItemsParams struct {
	Column1 SprintManagementWorkItemType   `json:"column_1"`
	Column2 SprintManagementWorkItemStatus `json:"column_2"`
	Column3 SprintManagementPriorityLevel  `json:"column_3"`
	Column4 pgtype.UUID                    `json:"column_4"`
	Column5 pgtype.UUID                    `json:"column_5"`
	Column6 pgtype.UUID                    `json:"column_6"`
	Column7 pgtype.UUID                    `json:"column_7"`
	Limit   int32                          `json:"limit"`
	Offset  int32                          `json:"offset"`
}

// Advanced filtering without search text
func (q *Queries) FilterWorkItems(ctx context.Context, arg FilterWorkItemsParams) ([]SprintManagementWorkItem, error) {
	rows, err := q.db.Query(ctx, filterWorkItems,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementWorkItem{}
	for rows.Next() {
		var i SprintManagementWorkItem
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWorkItems = `-- name: SearchWorkItems :many

SELECT 
    w.id, w.type, w.title, w.description, w.status, w.priority, w.story_points, w.assignee_id, w.reporter_id, w.parent_id, w.sprint_id, w.created_at, w.updated_at, w.deleted_at, w.deleted_by, w.project_id, w.ticket_number,
    ts_rank(
        to_tsvector('english', w.title || ' ' || COALESCE(w.description, '')),
        plainto_tsquery('english', $1)
    ) as rank
FROM sprint_management.work_items w
WHERE 
    deleted_at IS NULL
    AND to_tsvector('english', w.title || ' ' || COALESCE(w.description, '')) @@ plainto_tsquery('english', $1)
ORDER BY rank DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type SearchWorkItemsParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

type SearchWorkItemsRow struct {
	ID           pgtype.UUID                    `json:"id"`
	Type         SprintManagementWorkItemType   `json:"type"`
	Title        string                         `json:"title"`
	Description  *string                        `json:"description"`
	Status       SprintManagementWorkItemStatus `json:"status"`
	Priority     SprintManagementPriorityLevel  `json:"priority"`
	StoryPoints  *int32                         `json:"story_points"`
	AssigneeID   pgtype.UUID                    `json:"assignee_id"`
	ReporterID   pgtype.UUID                    `json:"reporter_id"`
	ParentID     pgtype.UUID                    `json:"parent_id"`
	SprintID     pgtype.UUID                    `json:"sprint_id"`
	CreatedAt    pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz             `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz             `json:"deleted_at"`
	DeletedBy    pgtype.UUID                    `json:"deleted_by"`
	ProjectID    pgtype.UUID                    `json:"project_id"`
	TicketNumber *int32                         `json:"ticket_number"`
	Rank         float32                        `json:"rank"`
}

// Search queries for work items with full-text search support
func (q *Queries) SearchWorkItems(ctx context.Context, arg SearchWorkItemsParams) ([]SearchWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, searchWorkItems, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchWorkItemsRow{}
	for rows.Next() {
		var i SearchWorkItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWorkItemsBoolean = `-- name: SearchWorkItemsBoolean :many
SELECT 
    w.id, w.type, w.title, w.description, w.status, w.priority, w.story_points, w.assignee_id, w.reporter_id, w.parent_id, w.sprint_id, w.created_at, w.updated_at, w.deleted_at, w.deleted_by, w.project_id, w.ticket_number,
    ts_rank(
        to_tsvector('english', w.title || ' ' || COALESCE(w.description, '')),
        websearch_to_tsquery('english', $1)
    ) as rank
FROM sprint_management.work_items w
WHERE 
    deleted_at IS NULL
    AND to_tsvector('english', w.title || ' ' || COALESCE(w.description, '')) @@ websearch_to_tsquery('english', $1)
ORDER BY rank DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type SearchWorkItemsBooleanParams struct {
	WebsearchToTsquery string `json:"websearch_to_tsquery"`
	Limit              int32  `json:"limit"`
	Offset             int32  `json:"offset"`
}

type SearchWorkItemsBooleanRow struct {
	ID           pgtype.UUID                    `json:"id"`
	Type         SprintManagementWorkItemType   `json:"type"`
	Title        string                         `json:"title"`
	Description  *string                        `json:"description"`
	Status       SprintManagementWorkItemStatus `json:"status"`
	Priority     SprintManagementPriorityLevel  `json:"priority"`
	StoryPoints  *int32                         `json:"story_points"`
	AssigneeID   pgtype.UUID                    `json:"assignee_id"`
	ReporterID   pgtype.UUID                    `json:"reporter_id"`
	ParentID     pgtype.UUID                    `json:"parent_id"`
	SprintID     pgtype.UUID                    `json:"sprint_id"`
	CreatedAt    pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz             `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz             `json:"deleted_at"`
	DeletedBy    pgtype.UUID                    `json:"deleted_by"`
	ProjectID    pgtype.UUID                    `json:"project_id"`
	TicketNumber *int32                         `json:"ticket_number"`
	Rank         float32                        `json:"rank"`
}

// Boolean search with AND/OR operators using websearch_to_tsquery
func (q *Queries) SearchWorkItemsBoolean(ctx context.Context, arg SearchWorkItemsBooleanParams) ([]SearchWorkItemsBooleanRow, error) {
	rows, err := q.db.Query(ctx, searchWorkItemsBoolean, arg.WebsearchToTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchWorkItemsBooleanRow{}
	for rows.Next() {
		var i SearchWorkItemsBooleanRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWorkItemsByField = `-- name: SearchWorkItemsByField :many
SELECT 
    w.id, w.type, w.title, w.description, w.status, w.priority, w.story_points, w.assignee_id, w.reporter_id, w.parent_id, w.sprint_id, w.created_at, w.updated_at, w.deleted_at, w.deleted_by, w.project_id, w.ticket_number,
    CASE 
        WHEN $2 = 'title' THEN ts_rank(to_tsvector('english', w.title), plainto_tsquery('english', $1))
        WHEN $2 = 'description' THEN ts_rank(to_tsvector('english', COALESCE(w.description, '')), plainto_tsquery('english', $1))
        ELSE ts_rank(to_tsvector('english', w.title || ' ' || COALESCE(w.description, '')), plainto_tsquery('english', $1))
    END as rank
FROM sprint_management.work_items w
WHERE 
    deleted_at IS NULL
    AND (
        CASE 
            WHEN $2 = 'title' THEN to_tsvector('english', w.title) @@ plainto_tsquery('english', $1)
            WHEN $2 = 'description' THEN to_tsvector('english', COALESCE(w.description, '')) @@ plainto_tsquery('english', $1)
            ELSE to_tsvector('english', w.title || ' ' || COALESCE(w.description, '')) @@ plainto_tsquery('english', $1)
        END
    )
ORDER BY rank DESC, created_at DESC
LIMIT $3 OFFSET $4
`

type SearchWorkItemsByFieldParams struct {
	PlaintoTsquery string      `json:"plainto_tsquery"`
	Column2        interface{} `json:"column_2"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type SearchWorkItemsByFieldRow struct {
	ID           pgtype.UUID                    `json:"id"`
	Type         SprintManagementWorkItemType   `json:"type"`
	Title        string                         `json:"title"`
	Description  *string                        `json:"description"`
	Status       SprintManagementWorkItemStatus `json:"status"`
	Priority     SprintManagementPriorityLevel  `json:"priority"`
	StoryPoints  *int32                         `json:"story_points"`
	AssigneeID   pgtype.UUID                    `json:"assignee_id"`
	ReporterID   pgtype.UUID                    `json:"reporter_id"`
	ParentID     pgtype.UUID                    `json:"parent_id"`
	SprintID     pgtype.UUID                    `json:"sprint_id"`
	CreatedAt    pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz             `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz             `json:"deleted_at"`
	DeletedBy    pgtype.UUID                    `json:"deleted_by"`
	ProjectID    pgtype.UUID                    `json:"project_id"`
	TicketNumber *int32                         `json:"ticket_number"`
	Rank         interface{}                    `json:"rank"`
}

// Field-specific search supporting title, description, or both
func (q *Queries) SearchWorkItemsByField(ctx context.Context, arg SearchWorkItemsByFieldParams) ([]SearchWorkItemsByFieldRow, error) {
	rows, err := q.db.Query(ctx, searchWorkItemsByField,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchWorkItemsByFieldRow{}
	for rows.Next() {
		var i SearchWorkItemsByFieldRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWorkItemsWithFilters = `-- name: SearchWorkItemsWithFilters :many
SELECT 
    w.id, w.type, w.title, w.description, w.status, w.priority, w.story_points, w.assignee_id, w.reporter_id, w.parent_id, w.sprint_id, w.created_at, w.updated_at, w.deleted_at, w.deleted_by, w.project_id, w.ticket_number,
    ts_rank(
        to_tsvector('english', w.title || ' ' || COALESCE(w.description, '')),
        plainto_tsquery('english', $1)
    ) as rank
FROM sprint_management.work_items w
WHERE 
    deleted_at IS NULL
    AND to_tsvector('english', w.title || ' ' || COALESCE(w.description, '')) @@ plainto_tsquery('english', $1)
    AND ($2::sprint_management.work_item_type IS NULL OR w.type = $2)
    AND ($3::sprint_management.work_item_status IS NULL OR w.status = $3)
    AND ($4::sprint_management.priority_level IS NULL OR w.priority = $4)
    AND ($5::uuid IS NULL OR w.assignee_id = $5)
    AND ($6::uuid IS NULL OR w.sprint_id = $6)
ORDER BY rank DESC, created_at DESC
LIMIT $7 OFFSET $8
`

type SearchWorkItemsWithFiltersParams struct {
	PlaintoTsquery string                         `json:"plainto_tsquery"`
	Column2        SprintManagementWorkItemType   `json:"column_2"`
	Column3        SprintManagementWorkItemStatus `json:"column_3"`
	Column4        SprintManagementPriorityLevel  `json:"column_4"`
	Column5        pgtype.UUID                    `json:"column_5"`
	Column6        pgtype.UUID                    `json:"column_6"`
	Limit          int32                          `json:"limit"`
	Offset         int32                          `json:"offset"`
}

type SearchWorkItemsWithFiltersRow struct {
	ID           pgtype.UUID                    `json:"id"`
	Type         SprintManagementWorkItemType   `json:"type"`
	Title        string                         `json:"title"`
	Description  *string                        `json:"description"`
	Status       SprintManagementWorkItemStatus `json:"status"`
	Priority     SprintManagementPriorityLevel  `json:"priority"`
	StoryPoints  *int32                         `json:"story_points"`
	AssigneeID   pgtype.UUID                    `json:"assignee_id"`
	ReporterID   pgtype.UUID                    `json:"reporter_id"`
	ParentID     pgtype.UUID                    `json:"parent_id"`
	SprintID     pgtype.UUID                    `json:"sprint_id"`
	CreatedAt    pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz             `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz             `json:"deleted_at"`
	DeletedBy    pgtype.UUID                    `json:"deleted_by"`
	ProjectID    pgtype.UUID                    `json:"project_id"`
	TicketNumber *int32                         `json:"ticket_number"`
	Rank         float32                        `json:"rank"`
}

func (q *Queries) SearchWorkItemsWithFilters(ctx context.Context, arg SearchWorkItemsWithFiltersParams) ([]SearchWorkItemsWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, searchWorkItemsWithFilters,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchWorkItemsWithFiltersRow{}
	for rows.Next() {
		var i SearchWorkItemsWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
