// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workitems.sql

package workitems

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkItemsBySprint = `-- name: CountWorkItemsBySprint :one
SELECT COUNT(*) FROM sprint_management.work_items
WHERE sprint_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountWorkItemsBySprint(ctx context.Context, sprintID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkItemsBySprint, sprintID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkItemsByStatus = `-- name: CountWorkItemsByStatus :one
SELECT COUNT(*) FROM sprint_management.work_items
WHERE status = $1 AND deleted_at IS NULL
`

func (q *Queries) CountWorkItemsByStatus(ctx context.Context, status SprintManagementWorkItemStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkItemsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkItem = `-- name: CreateWorkItem :one
INSERT INTO sprint_management.work_items (
    type,
    title,
    description,
    status,
    priority,
    story_points,
    assignee_id,
    reporter_id,
    parent_id,
    sprint_id,
    project_id,
    ticket_number
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, type, title, description, status, priority, story_points, assignee_id, reporter_id, parent_id, sprint_id, created_at, updated_at, deleted_at, deleted_by, project_id, ticket_number
`

type CreateWorkItemParams struct {
	Type         SprintManagementWorkItemType   `json:"type"`
	Title        string                         `json:"title"`
	Description  *string                        `json:"description"`
	Status       SprintManagementWorkItemStatus `json:"status"`
	Priority     SprintManagementPriorityLevel  `json:"priority"`
	StoryPoints  *int32                         `json:"story_points"`
	AssigneeID   pgtype.UUID                    `json:"assignee_id"`
	ReporterID   pgtype.UUID                    `json:"reporter_id"`
	ParentID     pgtype.UUID                    `json:"parent_id"`
	SprintID     pgtype.UUID                    `json:"sprint_id"`
	ProjectID    pgtype.UUID                    `json:"project_id"`
	TicketNumber *int32                         `json:"ticket_number"`
}

func (q *Queries) CreateWorkItem(ctx context.Context, arg CreateWorkItemParams) (SprintManagementWorkItem, error) {
	row := q.db.QueryRow(ctx, createWorkItem,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.StoryPoints,
		arg.AssigneeID,
		arg.ReporterID,
		arg.ParentID,
		arg.SprintID,
		arg.ProjectID,
		arg.TicketNumber,
	)
	var i SprintManagementWorkItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.StoryPoints,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.ProjectID,
		&i.TicketNumber,
	)
	return i, err
}

const getWorkItemByID = `-- name: GetWorkItemByID :one
SELECT 
    wi.id, wi.type, wi.title, wi.description, wi.status, wi.priority, wi.story_points, wi.assignee_id, wi.reporter_id, wi.parent_id, wi.sprint_id, wi.created_at, wi.updated_at, wi.deleted_at, wi.deleted_by, wi.project_id, wi.ticket_number,
    p.key as project_key
FROM sprint_management.work_items wi
LEFT JOIN sprint_management.projects p ON wi.project_id = p.id
WHERE wi.id = $1 AND wi.deleted_at IS NULL
`

type GetWorkItemByIDRow struct {
	ID           pgtype.UUID                    `json:"id"`
	Type         SprintManagementWorkItemType   `json:"type"`
	Title        string                         `json:"title"`
	Description  *string                        `json:"description"`
	Status       SprintManagementWorkItemStatus `json:"status"`
	Priority     SprintManagementPriorityLevel  `json:"priority"`
	StoryPoints  *int32                         `json:"story_points"`
	AssigneeID   pgtype.UUID                    `json:"assignee_id"`
	ReporterID   pgtype.UUID                    `json:"reporter_id"`
	ParentID     pgtype.UUID                    `json:"parent_id"`
	SprintID     pgtype.UUID                    `json:"sprint_id"`
	CreatedAt    pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz             `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz             `json:"deleted_at"`
	DeletedBy    pgtype.UUID                    `json:"deleted_by"`
	ProjectID    pgtype.UUID                    `json:"project_id"`
	TicketNumber *int32                         `json:"ticket_number"`
	ProjectKey   *string                        `json:"project_key"`
}

func (q *Queries) GetWorkItemByID(ctx context.Context, id pgtype.UUID) (GetWorkItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkItemByID, id)
	var i GetWorkItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.StoryPoints,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.ProjectID,
		&i.TicketNumber,
		&i.ProjectKey,
	)
	return i, err
}

const getWorkItemByIDIncludingDeleted = `-- name: GetWorkItemByIDIncludingDeleted :one
SELECT id, type, title, description, status, priority, story_points, assignee_id, reporter_id, parent_id, sprint_id, created_at, updated_at, deleted_at, deleted_by, project_id, ticket_number FROM sprint_management.work_items
WHERE id = $1
`

func (q *Queries) GetWorkItemByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (SprintManagementWorkItem, error) {
	row := q.db.QueryRow(ctx, getWorkItemByIDIncludingDeleted, id)
	var i SprintManagementWorkItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.StoryPoints,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.ProjectID,
		&i.TicketNumber,
	)
	return i, err
}

const hasChildren = `-- name: HasChildren :one
SELECT EXISTS(
    SELECT 1 FROM sprint_management.work_items
    WHERE parent_id = $1 AND deleted_at IS NULL
) as has_children
`

func (q *Queries) HasChildren(ctx context.Context, parentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasChildren, parentID)
	var has_children bool
	err := row.Scan(&has_children)
	return has_children, err
}

const hasDependencies = `-- name: HasDependencies :one
SELECT EXISTS(
    SELECT 1 FROM sprint_management.work_item_dependencies
    WHERE source_id = $1 OR target_id = $1
) as has_dependencies
`

func (q *Queries) HasDependencies(ctx context.Context, sourceID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasDependencies, sourceID)
	var has_dependencies bool
	err := row.Scan(&has_dependencies)
	return has_dependencies, err
}

const listSoftDeletedWorkItems = `-- name: ListSoftDeletedWorkItems :many
SELECT id, type, title, description, status, priority, story_points, assignee_id, reporter_id, parent_id, sprint_id, created_at, updated_at, deleted_at, deleted_by, project_id, ticket_number FROM sprint_management.work_items
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id
LIMIT $1 OFFSET $2
`

type ListSoftDeletedWorkItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSoftDeletedWorkItems(ctx context.Context, arg ListSoftDeletedWorkItemsParams) ([]SprintManagementWorkItem, error) {
	rows, err := q.db.Query(ctx, listSoftDeletedWorkItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementWorkItem{}
	for rows.Next() {
		var i SprintManagementWorkItem
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItems = `-- name: ListWorkItems :many
SELECT 
    wi.id, wi.type, wi.title, wi.description, wi.status, wi.priority, wi.story_points, wi.assignee_id, wi.reporter_id, wi.parent_id, wi.sprint_id, wi.created_at, wi.updated_at, wi.deleted_at, wi.deleted_by, wi.project_id, wi.ticket_number,
    p.key as project_key
FROM sprint_management.work_items wi
LEFT JOIN sprint_management.projects p ON wi.project_id = p.id
WHERE wi.deleted_at IS NULL
  AND (
    $2::timestamptz IS NULL
    OR (wi.created_at, wi.id) > ($2::timestamptz, $3::uuid)
  )
ORDER BY wi.created_at ASC, wi.id ASC
LIMIT $1
`

type ListWorkItemsParams struct {
	Limit           int32              `json:"limit"`
	CursorTimestamp pgtype.Timestamptz `json:"cursor_timestamp"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
}

type ListWorkItemsRow struct {
	ID           pgtype.UUID                    `json:"id"`
	Type         SprintManagementWorkItemType   `json:"type"`
	Title        string                         `json:"title"`
	Description  *string                        `json:"description"`
	Status       SprintManagementWorkItemStatus `json:"status"`
	Priority     SprintManagementPriorityLevel  `json:"priority"`
	StoryPoints  *int32                         `json:"story_points"`
	AssigneeID   pgtype.UUID                    `json:"assignee_id"`
	ReporterID   pgtype.UUID                    `json:"reporter_id"`
	ParentID     pgtype.UUID                    `json:"parent_id"`
	SprintID     pgtype.UUID                    `json:"sprint_id"`
	CreatedAt    pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz             `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz             `json:"deleted_at"`
	DeletedBy    pgtype.UUID                    `json:"deleted_by"`
	ProjectID    pgtype.UUID                    `json:"project_id"`
	TicketNumber *int32                         `json:"ticket_number"`
	ProjectKey   *string                        `json:"project_key"`
}

func (q *Queries) ListWorkItems(ctx context.Context, arg ListWorkItemsParams) ([]ListWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, listWorkItems, arg.Limit, arg.CursorTimestamp, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkItemsRow{}
	for rows.Next() {
		var i ListWorkItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
			&i.ProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItemsByAssignee = `-- name: ListWorkItemsByAssignee :many
SELECT id, type, title, description, status, priority, story_points, assignee_id, reporter_id, parent_id, sprint_id, created_at, updated_at, deleted_at, deleted_by, project_id, ticket_number FROM sprint_management.work_items
WHERE assignee_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListWorkItemsByAssigneeParams struct {
	AssigneeID pgtype.UUID `json:"assignee_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListWorkItemsByAssignee(ctx context.Context, arg ListWorkItemsByAssigneeParams) ([]SprintManagementWorkItem, error) {
	rows, err := q.db.Query(ctx, listWorkItemsByAssignee, arg.AssigneeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementWorkItem{}
	for rows.Next() {
		var i SprintManagementWorkItem
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItemsByParent = `-- name: ListWorkItemsByParent :many
SELECT id, type, title, description, status, priority, story_points, assignee_id, reporter_id, parent_id, sprint_id, created_at, updated_at, deleted_at, deleted_by, project_id, ticket_number FROM sprint_management.work_items
WHERE parent_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id
`

func (q *Queries) ListWorkItemsByParent(ctx context.Context, parentID pgtype.UUID) ([]SprintManagementWorkItem, error) {
	rows, err := q.db.Query(ctx, listWorkItemsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementWorkItem{}
	for rows.Next() {
		var i SprintManagementWorkItem
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItemsBySprint = `-- name: ListWorkItemsBySprint :many
SELECT 
    wi.id, wi.type, wi.title, wi.description, wi.status, wi.priority, wi.story_points, wi.assignee_id, wi.reporter_id, wi.parent_id, wi.sprint_id, wi.created_at, wi.updated_at, wi.deleted_at, wi.deleted_by, wi.project_id, wi.ticket_number,
    p.key as project_key
FROM sprint_management.work_items wi
LEFT JOIN sprint_management.projects p ON wi.project_id = p.id
WHERE wi.sprint_id = $1 AND wi.deleted_at IS NULL
ORDER BY wi.created_at DESC, wi.id
`

type ListWorkItemsBySprintRow struct {
	ID           pgtype.UUID                    `json:"id"`
	Type         SprintManagementWorkItemType   `json:"type"`
	Title        string                         `json:"title"`
	Description  *string                        `json:"description"`
	Status       SprintManagementWorkItemStatus `json:"status"`
	Priority     SprintManagementPriorityLevel  `json:"priority"`
	StoryPoints  *int32                         `json:"story_points"`
	AssigneeID   pgtype.UUID                    `json:"assignee_id"`
	ReporterID   pgtype.UUID                    `json:"reporter_id"`
	ParentID     pgtype.UUID                    `json:"parent_id"`
	SprintID     pgtype.UUID                    `json:"sprint_id"`
	CreatedAt    pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz             `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz             `json:"deleted_at"`
	DeletedBy    pgtype.UUID                    `json:"deleted_by"`
	ProjectID    pgtype.UUID                    `json:"project_id"`
	TicketNumber *int32                         `json:"ticket_number"`
	ProjectKey   *string                        `json:"project_key"`
}

func (q *Queries) ListWorkItemsBySprint(ctx context.Context, sprintID pgtype.UUID) ([]ListWorkItemsBySprintRow, error) {
	rows, err := q.db.Query(ctx, listWorkItemsBySprint, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkItemsBySprintRow{}
	for rows.Next() {
		var i ListWorkItemsBySprintRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
			&i.ProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItemsByStatus = `-- name: ListWorkItemsByStatus :many
SELECT id, type, title, description, status, priority, story_points, assignee_id, reporter_id, parent_id, sprint_id, created_at, updated_at, deleted_at, deleted_by, project_id, ticket_number FROM sprint_management.work_items
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListWorkItemsByStatusParams struct {
	Status SprintManagementWorkItemStatus `json:"status"`
	Limit  int32                          `json:"limit"`
	Offset int32                          `json:"offset"`
}

func (q *Queries) ListWorkItemsByStatus(ctx context.Context, arg ListWorkItemsByStatusParams) ([]SprintManagementWorkItem, error) {
	rows, err := q.db.Query(ctx, listWorkItemsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementWorkItem{}
	for rows.Next() {
		var i SprintManagementWorkItem
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItemsByType = `-- name: ListWorkItemsByType :many
SELECT id, type, title, description, status, priority, story_points, assignee_id, reporter_id, parent_id, sprint_id, created_at, updated_at, deleted_at, deleted_by, project_id, ticket_number FROM sprint_management.work_items
WHERE type = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListWorkItemsByTypeParams struct {
	Type   SprintManagementWorkItemType `json:"type"`
	Limit  int32                        `json:"limit"`
	Offset int32                        `json:"offset"`
}

func (q *Queries) ListWorkItemsByType(ctx context.Context, arg ListWorkItemsByTypeParams) ([]SprintManagementWorkItem, error) {
	rows, err := q.db.Query(ctx, listWorkItemsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementWorkItem{}
	for rows.Next() {
		var i SprintManagementWorkItem
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StoryPoints,
			&i.AssigneeID,
			&i.ReporterID,
			&i.ParentID,
			&i.SprintID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ProjectID,
			&i.TicketNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentlyDeleteWorkItem = `-- name: PermanentlyDeleteWorkItem :exec
DELETE FROM sprint_management.work_items
WHERE id = $1
`

func (q *Queries) PermanentlyDeleteWorkItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, permanentlyDeleteWorkItem, id)
	return err
}

const restoreWorkItem = `-- name: RestoreWorkItem :exec
UPDATE sprint_management.work_items
SET
    deleted_at = NULL,
    deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreWorkItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreWorkItem, id)
	return err
}

const softDeleteWorkItem = `-- name: SoftDeleteWorkItem :exec
UPDATE sprint_management.work_items
SET
    deleted_at = NOW() AT TIME ZONE 'UTC',
    deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteWorkItemParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteWorkItem(ctx context.Context, arg SoftDeleteWorkItemParams) error {
	_, err := q.db.Exec(ctx, softDeleteWorkItem, arg.ID, arg.DeletedBy)
	return err
}

const sumCompletedStoryPointsBySprint = `-- name: SumCompletedStoryPointsBySprint :one
SELECT COALESCE(SUM(story_points), 0) as total
FROM sprint_management.work_items
WHERE sprint_id = $1 AND status = 'done' AND deleted_at IS NULL
`

func (q *Queries) SumCompletedStoryPointsBySprint(ctx context.Context, sprintID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumCompletedStoryPointsBySprint, sprintID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumStoryPointsBySprint = `-- name: SumStoryPointsBySprint :one
SELECT COALESCE(SUM(story_points), 0) as total
FROM sprint_management.work_items
WHERE sprint_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SumStoryPointsBySprint(ctx context.Context, sprintID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumStoryPointsBySprint, sprintID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const updateWorkItem = `-- name: UpdateWorkItem :one
UPDATE sprint_management.work_items
SET
    type = COALESCE($2, type),
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    status = COALESCE($5, status),
    priority = COALESCE($6, priority),
    story_points = COALESCE($7, story_points),
    assignee_id = COALESCE($8, assignee_id),
    parent_id = COALESCE($9, parent_id),
    sprint_id = COALESCE($10, sprint_id)
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, type, title, description, status, priority, story_points, assignee_id, reporter_id, parent_id, sprint_id, created_at, updated_at, deleted_at, deleted_by, project_id, ticket_number
`

type UpdateWorkItemParams struct {
	ID          pgtype.UUID                        `json:"id"`
	Type        NullSprintManagementWorkItemType   `json:"type"`
	Title       *string                            `json:"title"`
	Description *string                            `json:"description"`
	Status      NullSprintManagementWorkItemStatus `json:"status"`
	Priority    NullSprintManagementPriorityLevel  `json:"priority"`
	StoryPoints *int32                             `json:"story_points"`
	AssigneeID  pgtype.UUID                        `json:"assignee_id"`
	ParentID    pgtype.UUID                        `json:"parent_id"`
	SprintID    pgtype.UUID                        `json:"sprint_id"`
}

func (q *Queries) UpdateWorkItem(ctx context.Context, arg UpdateWorkItemParams) (SprintManagementWorkItem, error) {
	row := q.db.QueryRow(ctx, updateWorkItem,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.StoryPoints,
		arg.AssigneeID,
		arg.ParentID,
		arg.SprintID,
	)
	var i SprintManagementWorkItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.StoryPoints,
		&i.AssigneeID,
		&i.ReporterID,
		&i.ParentID,
		&i.SprintID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.ProjectID,
		&i.TicketNumber,
	)
	return i, err
}
