// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sources

import (
	"context"
)

type Querier interface {
	BulkCreateSource(ctx context.Context, arg BulkCreateSourceParams) (DndSource, error)
	GetSourceByNameShortVersion(ctx context.Context, arg GetSourceByNameShortVersionParams) (DndSource, error)
	GetSourceByNameVersion(ctx context.Context, arg GetSourceByNameVersionParams) (DndSource, error)
	QuerySources(ctx context.Context, dndVersion *string) ([]DndSource, error)
	SourceExistsByName(ctx context.Context, name string) (bool, error)
}

var _ Querier = (*Queries)(nil)
