// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package sources

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCreateSource = `-- name: BulkCreateSource :one
INSERT INTO dnd.source (
    id,
    name,
    name_short,
    publish_year,
    dnd_version,
    dnd_version_year,
    created_at,
    updated_at,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, name, name_short, publish_year, dnd_version, dnd_version_year, created_at, updated_at, created_by, updated_by
`

type BulkCreateSourceParams struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	NameShort      string             `json:"name_short"`
	PublishYear    *int32             `json:"publish_year"`
	DndVersion     string             `json:"dnd_version"`
	DndVersionYear int32              `json:"dnd_version_year"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) BulkCreateSource(ctx context.Context, arg BulkCreateSourceParams) (DndSource, error) {
	row := q.db.QueryRow(ctx, bulkCreateSource,
		arg.ID,
		arg.Name,
		arg.NameShort,
		arg.PublishYear,
		arg.DndVersion,
		arg.DndVersionYear,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i DndSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameShort,
		&i.PublishYear,
		&i.DndVersion,
		&i.DndVersionYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getSourceByNameShortVersion = `-- name: GetSourceByNameShortVersion :one
SELECT id, name, name_short, publish_year, dnd_version, dnd_version_year, created_at, updated_at, created_by, updated_by FROM dnd.source
WHERE LOWER(name_short) = LOWER($1)
  AND dnd_version = $2
  AND dnd_version_year = $3
LIMIT 1
`

type GetSourceByNameShortVersionParams struct {
	Lower          string `json:"lower"`
	DndVersion     string `json:"dnd_version"`
	DndVersionYear int32  `json:"dnd_version_year"`
}

func (q *Queries) GetSourceByNameShortVersion(ctx context.Context, arg GetSourceByNameShortVersionParams) (DndSource, error) {
	row := q.db.QueryRow(ctx, getSourceByNameShortVersion, arg.Lower, arg.DndVersion, arg.DndVersionYear)
	var i DndSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameShort,
		&i.PublishYear,
		&i.DndVersion,
		&i.DndVersionYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getSourceByNameVersion = `-- name: GetSourceByNameVersion :one
SELECT id, name, name_short, publish_year, dnd_version, dnd_version_year, created_at, updated_at, created_by, updated_by FROM dnd.source
WHERE name = $1
  AND dnd_version = $2
  AND dnd_version_year = $3
LIMIT 1
`

type GetSourceByNameVersionParams struct {
	Name           string `json:"name"`
	DndVersion     string `json:"dnd_version"`
	DndVersionYear int32  `json:"dnd_version_year"`
}

func (q *Queries) GetSourceByNameVersion(ctx context.Context, arg GetSourceByNameVersionParams) (DndSource, error) {
	row := q.db.QueryRow(ctx, getSourceByNameVersion, arg.Name, arg.DndVersion, arg.DndVersionYear)
	var i DndSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameShort,
		&i.PublishYear,
		&i.DndVersion,
		&i.DndVersionYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const querySources = `-- name: QuerySources :many
SELECT id, name, name_short, publish_year, dnd_version, dnd_version_year, created_at, updated_at, created_by, updated_by FROM dnd.source
WHERE (
    $1::text IS NULL
    OR dnd_version = $1::text
)
ORDER BY name ASC
`

func (q *Queries) QuerySources(ctx context.Context, dndVersion *string) ([]DndSource, error) {
	rows, err := q.db.Query(ctx, querySources, dndVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DndSource{}
	for rows.Next() {
		var i DndSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameShort,
			&i.PublishYear,
			&i.DndVersion,
			&i.DndVersionYear,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceExistsByName = `-- name: SourceExistsByName :one
SELECT EXISTS(
    SELECT 1 FROM dnd.source WHERE name = $1
) AS exists
`

func (q *Queries) SourceExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, sourceExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
