// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package spells

import (
	"context"
)

type Querier interface {
	CountAllSpells(ctx context.Context) (int64, error)
	CountQuerySpells(ctx context.Context, arg CountQuerySpellsParams) (int64, error)
	CreateSpell(ctx context.Context, arg CreateSpellParams) (DndSpell, error)
	GetSpellByUniqueKey(ctx context.Context, arg GetSpellByUniqueKeyParams) (DndSpell, error)
	ListSpells(ctx context.Context, arg ListSpellsParams) ([]DndSpell, error)
	QuerySpells(ctx context.Context, arg QuerySpellsParams) ([]DndSpell, error)
	SpellExistsByNameVersion(ctx context.Context, arg SpellExistsByNameVersionParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
