// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spells.sql

package spells

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllSpells = `-- name: CountAllSpells :one
SELECT COUNT(*) FROM dnd.spell
`

func (q *Queries) CountAllSpells(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllSpells)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuerySpells = `-- name: CountQuerySpells :one
SELECT COUNT(*) FROM dnd.spell
WHERE (
    $1::text IS NULL
    OR name ILIKE '%' || $1::text || '%'
)
AND (
    $2::int IS NULL
    OR level = $2::int
)
AND (
    $3::text IS NULL
    OR school = $3::text
)
`

type CountQuerySpellsParams struct {
	Name   *string `json:"name"`
	Level  *int32  `json:"level"`
	School *string `json:"school"`
}

func (q *Queries) CountQuerySpells(ctx context.Context, arg CountQuerySpellsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuerySpells, arg.Name, arg.Level, arg.School)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpell = `-- name: CreateSpell :one
INSERT INTO dnd.spell (
    id,
    source_id,
    name,
    slug,
    dnd_version,
    dnd_version_year,
    source_page,
    level,
    school,
    is_ritual,
    is_unearthed_arcana,
    casting_time,
    range,
    has_verbal_component,
    has_somatic_component,
    has_material_component,
    materials,
    has_spell_cost,
    are_materials_consumed,
    duration,
    is_concentration,
    description,
    has_saving_throw,
    difficulty_class_saving_throw_override,
    damage_type,
    at_higher_levels,
    difficulty_class_saving_throw,
    difficulty_class_type,
    stat_blocks,
    created_at,
    updated_at,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33
) RETURNING id, source_id, name, slug, dnd_version, dnd_version_year, source_page, level, school, is_ritual, is_unearthed_arcana, casting_time, range, has_verbal_component, has_somatic_component, has_material_component, materials, has_spell_cost, are_materials_consumed, duration, is_concentration, description, has_saving_throw, difficulty_class_saving_throw_override, damage_type, at_higher_levels, difficulty_class_saving_throw, difficulty_class_type, stat_blocks, created_at, updated_at, created_by, updated_by
`

type CreateSpellParams struct {
	ID                                 pgtype.UUID        `json:"id"`
	SourceID                           pgtype.UUID        `json:"source_id"`
	Name                               string             `json:"name"`
	Slug                               *string            `json:"slug"`
	DndVersion                         string             `json:"dnd_version"`
	DndVersionYear                     int32              `json:"dnd_version_year"`
	SourcePage                         *int32             `json:"source_page"`
	Level                              int32              `json:"level"`
	School                             DndSpellSchool     `json:"school"`
	IsRitual                           bool               `json:"is_ritual"`
	IsUnearthedArcana                  bool               `json:"is_unearthed_arcana"`
	CastingTime                        string             `json:"casting_time"`
	Range                              string             `json:"range"`
	HasVerbalComponent                 bool               `json:"has_verbal_component"`
	HasSomaticComponent                bool               `json:"has_somatic_component"`
	HasMaterialComponent               bool               `json:"has_material_component"`
	Materials                          *string            `json:"materials"`
	HasSpellCost                       bool               `json:"has_spell_cost"`
	AreMaterialsConsumed               bool               `json:"are_materials_consumed"`
	Duration                           string             `json:"duration"`
	IsConcentration                    bool               `json:"is_concentration"`
	Description                        string             `json:"description"`
	HasSavingThrow                     bool               `json:"has_saving_throw"`
	DifficultyClassSavingThrowOverride *int32             `json:"difficulty_class_saving_throw_override"`
	DamageType                         *string            `json:"damage_type"`
	AtHigherLevels                     *string            `json:"at_higher_levels"`
	DifficultyClassSavingThrow         *string            `json:"difficulty_class_saving_throw"`
	DifficultyClassType                *string            `json:"difficulty_class_type"`
	StatBlocks                         []byte             `json:"stat_blocks"`
	CreatedAt                          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                          pgtype.Timestamptz `json:"updated_at"`
	CreatedBy                          pgtype.UUID        `json:"created_by"`
	UpdatedBy                          pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) CreateSpell(ctx context.Context, arg CreateSpellParams) (DndSpell, error) {
	row := q.db.QueryRow(ctx, createSpell,
		arg.ID,
		arg.SourceID,
		arg.Name,
		arg.Slug,
		arg.DndVersion,
		arg.DndVersionYear,
		arg.SourcePage,
		arg.Level,
		arg.School,
		arg.IsRitual,
		arg.IsUnearthedArcana,
		arg.CastingTime,
		arg.Range,
		arg.HasVerbalComponent,
		arg.HasSomaticComponent,
		arg.HasMaterialComponent,
		arg.Materials,
		arg.HasSpellCost,
		arg.AreMaterialsConsumed,
		arg.Duration,
		arg.IsConcentration,
		arg.Description,
		arg.HasSavingThrow,
		arg.DifficultyClassSavingThrowOverride,
		arg.DamageType,
		arg.AtHigherLevels,
		arg.DifficultyClassSavingThrow,
		arg.DifficultyClassType,
		arg.StatBlocks,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i DndSpell
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Name,
		&i.Slug,
		&i.DndVersion,
		&i.DndVersionYear,
		&i.SourcePage,
		&i.Level,
		&i.School,
		&i.IsRitual,
		&i.IsUnearthedArcana,
		&i.CastingTime,
		&i.Range,
		&i.HasVerbalComponent,
		&i.HasSomaticComponent,
		&i.HasMaterialComponent,
		&i.Materials,
		&i.HasSpellCost,
		&i.AreMaterialsConsumed,
		&i.Duration,
		&i.IsConcentration,
		&i.Description,
		&i.HasSavingThrow,
		&i.DifficultyClassSavingThrowOverride,
		&i.DamageType,
		&i.AtHigherLevels,
		&i.DifficultyClassSavingThrow,
		&i.DifficultyClassType,
		&i.StatBlocks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listSpells = `-- name: ListSpells :many
SELECT id, source_id, name, slug, dnd_version, dnd_version_year, source_page, level, school, is_ritual, is_unearthed_arcana, casting_time, range, has_verbal_component, has_somatic_component, has_material_component, materials, has_spell_cost, are_materials_consumed, duration, is_concentration, description, has_saving_throw, difficulty_class_saving_throw_override, damage_type, at_higher_levels, difficulty_class_saving_throw, difficulty_class_type, stat_blocks, created_at, updated_at, created_by, updated_by FROM dnd.spell
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListSpellsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSpells(ctx context.Context, arg ListSpellsParams) ([]DndSpell, error) {
	rows, err := q.db.Query(ctx, listSpells, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DndSpell{}
	for rows.Next() {
		var i DndSpell
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Name,
			&i.Slug,
			&i.DndVersion,
			&i.DndVersionYear,
			&i.SourcePage,
			&i.Level,
			&i.School,
			&i.IsRitual,
			&i.IsUnearthedArcana,
			&i.CastingTime,
			&i.Range,
			&i.HasVerbalComponent,
			&i.HasSomaticComponent,
			&i.HasMaterialComponent,
			&i.Materials,
			&i.HasSpellCost,
			&i.AreMaterialsConsumed,
			&i.Duration,
			&i.IsConcentration,
			&i.Description,
			&i.HasSavingThrow,
			&i.DifficultyClassSavingThrowOverride,
			&i.DamageType,
			&i.AtHigherLevels,
			&i.DifficultyClassSavingThrow,
			&i.DifficultyClassType,
			&i.StatBlocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySpells = `-- name: QuerySpells :many
SELECT id, source_id, name, slug, dnd_version, dnd_version_year, source_page, level, school, is_ritual, is_unearthed_arcana, casting_time, range, has_verbal_component, has_somatic_component, has_material_component, materials, has_spell_cost, are_materials_consumed, duration, is_concentration, description, has_saving_throw, difficulty_class_saving_throw_override, damage_type, at_higher_levels, difficulty_class_saving_throw, difficulty_class_type, stat_blocks, created_at, updated_at, created_by, updated_by FROM dnd.spell
WHERE (
    $3::text IS NULL
    OR name ILIKE '%' || $3::text || '%'
)
AND (
    $4::int IS NULL
    OR level = $4::int
)
AND (
    $5::text IS NULL
    OR school = $5::text
)
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type QuerySpellsParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Name   *string `json:"name"`
	Level  *int32  `json:"level"`
	School *string `json:"school"`
}

func (q *Queries) QuerySpells(ctx context.Context, arg QuerySpellsParams) ([]DndSpell, error) {
	rows, err := q.db.Query(ctx, querySpells,
		arg.Limit,
		arg.Offset,
		arg.Name,
		arg.Level,
		arg.School,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DndSpell{}
	for rows.Next() {
		var i DndSpell
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Name,
			&i.Slug,
			&i.DndVersion,
			&i.DndVersionYear,
			&i.SourcePage,
			&i.Level,
			&i.School,
			&i.IsRitual,
			&i.IsUnearthedArcana,
			&i.CastingTime,
			&i.Range,
			&i.HasVerbalComponent,
			&i.HasSomaticComponent,
			&i.HasMaterialComponent,
			&i.Materials,
			&i.HasSpellCost,
			&i.AreMaterialsConsumed,
			&i.Duration,
			&i.IsConcentration,
			&i.Description,
			&i.HasSavingThrow,
			&i.DifficultyClassSavingThrowOverride,
			&i.DamageType,
			&i.AtHigherLevels,
			&i.DifficultyClassSavingThrow,
			&i.DifficultyClassType,
			&i.StatBlocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spellExistsByNameVersion = `-- name: SpellExistsByNameVersion :one
SELECT EXISTS(
    SELECT 1 FROM dnd.spell WHERE name = $1 AND dnd_version = $2 AND dnd_version_year = $3 AND source_id = $4
) AS exists
`

type SpellExistsByNameVersionParams struct {
	Name           string      `json:"name"`
	DndVersion     string      `json:"dnd_version"`
	DndVersionYear int32       `json:"dnd_version_year"`
	SourceID       pgtype.UUID `json:"source_id"`
}

func (q *Queries) SpellExistsByNameVersion(ctx context.Context, arg SpellExistsByNameVersionParams) (bool, error) {
	row := q.db.QueryRow(ctx, spellExistsByNameVersion, arg.Name, arg.DndVersion, arg.DndVersionYear, arg.SourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSpellByUniqueKey = `-- name: GetSpellByUniqueKey :one
SELECT id, source_id, name, slug, dnd_version, dnd_version_year, source_page, level, school, is_ritual, is_unearthed_arcana, casting_time, range, has_verbal_component, has_somatic_component, has_material_component, materials, has_spell_cost, are_materials_consumed, duration, is_concentration, description, has_saving_throw, difficulty_class_saving_throw_override, damage_type, at_higher_levels, difficulty_class_saving_throw, difficulty_class_type, stat_blocks, created_at, updated_at, created_by, updated_by FROM dnd.spell
WHERE name = $1 AND dnd_version = $2 AND dnd_version_year = $3 AND source_id = $4
LIMIT 1
`

type GetSpellByUniqueKeyParams struct {
	Name           string      `json:"name"`
	DndVersion     string      `json:"dnd_version"`
	DndVersionYear int32       `json:"dnd_version_year"`
	SourceID       pgtype.UUID `json:"source_id"`
}

func (q *Queries) GetSpellByUniqueKey(ctx context.Context, arg GetSpellByUniqueKeyParams) (DndSpell, error) {
	row := q.db.QueryRow(ctx, getSpellByUniqueKey, arg.Name, arg.DndVersion, arg.DndVersionYear, arg.SourceID)
	var i DndSpell
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Name,
		&i.Slug,
		&i.DndVersion,
		&i.DndVersionYear,
		&i.SourcePage,
		&i.Level,
		&i.School,
		&i.IsRitual,
		&i.IsUnearthedArcana,
		&i.CastingTime,
		&i.Range,
		&i.HasVerbalComponent,
		&i.HasSomaticComponent,
		&i.HasMaterialComponent,
		&i.Materials,
		&i.HasSpellCost,
		&i.AreMaterialsConsumed,
		&i.Duration,
		&i.IsConcentration,
		&i.Description,
		&i.HasSavingThrow,
		&i.DifficultyClassSavingThrowOverride,
		&i.DamageType,
		&i.AtHigherLevels,
		&i.DifficultyClassSavingThrow,
		&i.DifficultyClassType,
		&i.StatBlocks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
