// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DndSpellSchool string

const (
	DndSpellSchoolAbjuration    DndSpellSchool = "abjuration"
	DndSpellSchoolAlteration    DndSpellSchool = "alteration"
	DndSpellSchoolConjuration   DndSpellSchool = "conjuration"
	DndSpellSchoolDivination    DndSpellSchool = "divination"
	DndSpellSchoolEnchantment   DndSpellSchool = "enchantment"
	DndSpellSchoolEvocation     DndSpellSchool = "evocation"
	DndSpellSchoolTransmutation DndSpellSchool = "transmutation"
	DndSpellSchoolIllusion      DndSpellSchool = "illusion"
	DndSpellSchoolInvocation    DndSpellSchool = "invocation"
	DndSpellSchoolNecromancy    DndSpellSchool = "necromancy"
)

func (e *DndSpellSchool) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DndSpellSchool(s)
	case string:
		*e = DndSpellSchool(s)
	default:
		return fmt.Errorf("unsupported scan type for DndSpellSchool: %T", src)
	}
	return nil
}

type NullDndSpellSchool struct {
	DndSpellSchool DndSpellSchool `json:"dnd_spell_school"`
	Valid          bool           `json:"valid"` // Valid is true if DndSpellSchool is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDndSpellSchool) Scan(value interface{}) error {
	if value == nil {
		ns.DndSpellSchool, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DndSpellSchool.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDndSpellSchool) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DndSpellSchool), nil
}

type DndSource struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	NameShort      string             `json:"name_short"`
	PublishYear    *int32             `json:"publish_year"`
	DndVersion     string             `json:"dnd_version"`
	DndVersionYear int32              `json:"dnd_version_year"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
}

type DndSpell struct {
	ID                                 pgtype.UUID        `json:"id"`
	SourceID                           pgtype.UUID        `json:"source_id"`
	Name                               string             `json:"name"`
	Slug                               *string            `json:"slug"`
	DndVersion                         string             `json:"dnd_version"`
	DndVersionYear                     int32              `json:"dnd_version_year"`
	SourcePage                         *int32             `json:"source_page"`
	Level                              int32              `json:"level"`
	School                             DndSpellSchool     `json:"school"`
	IsRitual                           bool               `json:"is_ritual"`
	IsUnearthedArcana                  bool               `json:"is_unearthed_arcana"`
	CastingTime                        string             `json:"casting_time"`
	Range                              string             `json:"range"`
	HasVerbalComponent                 bool               `json:"has_verbal_component"`
	HasSomaticComponent                bool               `json:"has_somatic_component"`
	HasMaterialComponent               bool               `json:"has_material_component"`
	Materials                          *string            `json:"materials"`
	HasSpellCost                       bool               `json:"has_spell_cost"`
	AreMaterialsConsumed               bool               `json:"are_materials_consumed"`
	Duration                           string             `json:"duration"`
	IsConcentration                    bool               `json:"is_concentration"`
	Description                        string             `json:"description"`
	HasSavingThrow                     bool               `json:"has_saving_throw"`
	DifficultyClassSavingThrowOverride *int32             `json:"difficulty_class_saving_throw_override"`
	DamageType                         *string            `json:"damage_type"`
	AtHigherLevels                     *string            `json:"at_higher_levels"`
	DifficultyClassSavingThrow         *string            `json:"difficulty_class_saving_throw"`
	DifficultyClassType                *string            `json:"difficulty_class_type"`
	StatBlocks                         []byte             `json:"stat_blocks"`
	CreatedAt                          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                          pgtype.Timestamptz `json:"updated_at"`
	CreatedBy                          pgtype.UUID        `json:"created_by"`
	UpdatedBy                          pgtype.UUID        `json:"updated_by"`
}

type DndUser struct {
	ID                pgtype.UUID `json:"id"`
	Username          *string     `json:"username"`
	ProfilePictureUrl *string     `json:"profile_picture_url"`
}
