// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetUserByID(ctx context.Context, id pgtype.UUID) (DndUser, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (DndUser, error)
}

var _ Querier = (*Queries)(nil)
