// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, profile_picture_url FROM dnd.user
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (DndUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i DndUser
	err := row.Scan(&i.ID, &i.Username, &i.ProfilePictureUrl)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
INSERT INTO dnd.user (id, username, profile_picture_url)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET
    username = EXCLUDED.username,
    profile_picture_url = EXCLUDED.profile_picture_url
RETURNING id, username, profile_picture_url
`

type UpdateUserParams struct {
	ID                pgtype.UUID `json:"id"`
	Username          *string     `json:"username"`
	ProfilePictureUrl *string     `json:"profile_picture_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (DndUser, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Username, arg.ProfilePictureUrl)
	var i DndUser
	err := row.Scan(&i.ID, &i.Username, &i.ProfilePictureUrl)
	return i, err
}
