// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sprints

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SprintManagementDependencyType string

const (
	SprintManagementDependencyTypeBlocks      SprintManagementDependencyType = "blocks"
	SprintManagementDependencyTypeIsBlockedBy SprintManagementDependencyType = "is_blocked_by"
	SprintManagementDependencyTypeRelatesTo   SprintManagementDependencyType = "relates_to"
	SprintManagementDependencyTypeDuplicates  SprintManagementDependencyType = "duplicates"
)

func (e *SprintManagementDependencyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SprintManagementDependencyType(s)
	case string:
		*e = SprintManagementDependencyType(s)
	default:
		return fmt.Errorf("unsupported scan type for SprintManagementDependencyType: %T", src)
	}
	return nil
}

type NullSprintManagementDependencyType struct {
	SprintManagementDependencyType SprintManagementDependencyType `json:"sprint_management_dependency_type"`
	Valid                          bool                           `json:"valid"` // Valid is true if SprintManagementDependencyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSprintManagementDependencyType) Scan(value interface{}) error {
	if value == nil {
		ns.SprintManagementDependencyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SprintManagementDependencyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSprintManagementDependencyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SprintManagementDependencyType), nil
}

type SprintManagementPriorityLevel string

const (
	SprintManagementPriorityLevelLow      SprintManagementPriorityLevel = "low"
	SprintManagementPriorityLevelMedium   SprintManagementPriorityLevel = "medium"
	SprintManagementPriorityLevelHigh     SprintManagementPriorityLevel = "high"
	SprintManagementPriorityLevelCritical SprintManagementPriorityLevel = "critical"
)

func (e *SprintManagementPriorityLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SprintManagementPriorityLevel(s)
	case string:
		*e = SprintManagementPriorityLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SprintManagementPriorityLevel: %T", src)
	}
	return nil
}

type NullSprintManagementPriorityLevel struct {
	SprintManagementPriorityLevel SprintManagementPriorityLevel `json:"sprint_management_priority_level"`
	Valid                         bool                          `json:"valid"` // Valid is true if SprintManagementPriorityLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSprintManagementPriorityLevel) Scan(value interface{}) error {
	if value == nil {
		ns.SprintManagementPriorityLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SprintManagementPriorityLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSprintManagementPriorityLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SprintManagementPriorityLevel), nil
}

type SprintManagementSprintStatus string

const (
	SprintManagementSprintStatusPlanned   SprintManagementSprintStatus = "planned"
	SprintManagementSprintStatusActive    SprintManagementSprintStatus = "active"
	SprintManagementSprintStatusCompleted SprintManagementSprintStatus = "completed"
	SprintManagementSprintStatusCancelled SprintManagementSprintStatus = "cancelled"
)

func (e *SprintManagementSprintStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SprintManagementSprintStatus(s)
	case string:
		*e = SprintManagementSprintStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SprintManagementSprintStatus: %T", src)
	}
	return nil
}

type NullSprintManagementSprintStatus struct {
	SprintManagementSprintStatus SprintManagementSprintStatus `json:"sprint_management_sprint_status"`
	Valid                        bool                         `json:"valid"` // Valid is true if SprintManagementSprintStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSprintManagementSprintStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SprintManagementSprintStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SprintManagementSprintStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSprintManagementSprintStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SprintManagementSprintStatus), nil
}

type SprintManagementWorkItemStatus string

const (
	SprintManagementWorkItemStatusTodo       SprintManagementWorkItemStatus = "todo"
	SprintManagementWorkItemStatusInProgress SprintManagementWorkItemStatus = "in_progress"
	SprintManagementWorkItemStatusInReview   SprintManagementWorkItemStatus = "in_review"
	SprintManagementWorkItemStatusDone       SprintManagementWorkItemStatus = "done"
	SprintManagementWorkItemStatusBlocked    SprintManagementWorkItemStatus = "blocked"
)

func (e *SprintManagementWorkItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SprintManagementWorkItemStatus(s)
	case string:
		*e = SprintManagementWorkItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SprintManagementWorkItemStatus: %T", src)
	}
	return nil
}

type NullSprintManagementWorkItemStatus struct {
	SprintManagementWorkItemStatus SprintManagementWorkItemStatus `json:"sprint_management_work_item_status"`
	Valid                          bool                           `json:"valid"` // Valid is true if SprintManagementWorkItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSprintManagementWorkItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SprintManagementWorkItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SprintManagementWorkItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSprintManagementWorkItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SprintManagementWorkItemStatus), nil
}

type SprintManagementWorkItemType string

const (
	SprintManagementWorkItemTypeEpic   SprintManagementWorkItemType = "epic"
	SprintManagementWorkItemTypeStory  SprintManagementWorkItemType = "story"
	SprintManagementWorkItemTypeDefect SprintManagementWorkItemType = "defect"
)

func (e *SprintManagementWorkItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SprintManagementWorkItemType(s)
	case string:
		*e = SprintManagementWorkItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for SprintManagementWorkItemType: %T", src)
	}
	return nil
}

type NullSprintManagementWorkItemType struct {
	SprintManagementWorkItemType SprintManagementWorkItemType `json:"sprint_management_work_item_type"`
	Valid                        bool                         `json:"valid"` // Valid is true if SprintManagementWorkItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSprintManagementWorkItemType) Scan(value interface{}) error {
	if value == nil {
		ns.SprintManagementWorkItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SprintManagementWorkItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSprintManagementWorkItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SprintManagementWorkItemType), nil
}

type AuthUser struct {
	ID                pgtype.UUID        `json:"id"`
	KeycloakID        string             `json:"keycloak_id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	FirstName         *string            `json:"first_name"`
	LastName          *string            `json:"last_name"`
	ProfilePictureUrl *string            `json:"profile_picture_url"`
	Roles             []string           `json:"roles"`
	IsActive          *bool              `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type SprintManagementActivityLog struct {
	ID         pgtype.UUID        `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Action     string             `json:"action"`
	UserID     pgtype.UUID        `json:"user_id"`
	Changes    []byte             `json:"changes"`
	TraceID    pgtype.UUID        `json:"trace_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SprintManagementComment struct {
	ID         pgtype.UUID        `json:"id"`
	WorkItemID pgtype.UUID        `json:"work_item_id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy  pgtype.UUID        `json:"deleted_by"`
}

// Projects for organizing work items
type SprintManagementProject struct {
	ID pgtype.UUID `json:"id"`
	// Unique uppercase project key (e.g., DND, SPRINT)
	Key         string  `json:"key"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	// Current ticket counter for sequential numbering
	CurrentCounter int32 `json:"current_counter"`
	// Starting number for ticket sequence
	StartingNumber int32              `json:"starting_number"`
	CreatedBy      string             `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedBy      string             `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SprintManagementSprint struct {
	ID              pgtype.UUID                  `json:"id"`
	Name            string                       `json:"name"`
	Description     *string                      `json:"description"`
	Status          SprintManagementSprintStatus `json:"status"`
	StartDate       pgtype.Date                  `json:"start_date"`
	EndDate         pgtype.Date                  `json:"end_date"`
	CapacityPoints  *int32                       `json:"capacity_points"`
	CommittedPoints *int32                       `json:"committed_points"`
	CompletedPoints *int32                       `json:"completed_points"`
	CreatedBy       pgtype.UUID                  `json:"created_by"`
	CreatedAt       pgtype.Timestamptz           `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz           `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz           `json:"deleted_at"`
	DeletedBy       pgtype.UUID                  `json:"deleted_by"`
}

type SprintManagementWorkItem struct {
	ID          pgtype.UUID                    `json:"id"`
	Type        SprintManagementWorkItemType   `json:"type"`
	Title       string                         `json:"title"`
	Description *string                        `json:"description"`
	Status      SprintManagementWorkItemStatus `json:"status"`
	Priority    SprintManagementPriorityLevel  `json:"priority"`
	StoryPoints *int32                         `json:"story_points"`
	AssigneeID  pgtype.UUID                    `json:"assignee_id"`
	ReporterID  pgtype.UUID                    `json:"reporter_id"`
	ParentID    pgtype.UUID                    `json:"parent_id"`
	SprintID    pgtype.UUID                    `json:"sprint_id"`
	CreatedAt   pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz             `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz             `json:"deleted_at"`
	DeletedBy   pgtype.UUID                    `json:"deleted_by"`
	// Reference to parent project
	ProjectID pgtype.UUID `json:"project_id"`
	// Sequential ticket number within project
	TicketNumber *int32 `json:"ticket_number"`
}

type SprintManagementWorkItemDependency struct {
	ID             pgtype.UUID                    `json:"id"`
	SourceID       pgtype.UUID                    `json:"source_id"`
	TargetID       pgtype.UUID                    `json:"target_id"`
	DependencyType SprintManagementDependencyType `json:"dependency_type"`
	CreatedAt      pgtype.Timestamptz             `json:"created_at"`
	CreatedBy      pgtype.UUID                    `json:"created_by"`
}
