// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sprints

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountSprintsByStatus(ctx context.Context, status SprintManagementSprintStatus) (int64, error)
	CreateSprint(ctx context.Context, arg CreateSprintParams) (SprintManagementSprint, error)
	GetSprintByID(ctx context.Context, id pgtype.UUID) (SprintManagementSprint, error)
	GetSprintByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (SprintManagementSprint, error)
	GetSprintWithWorkItems(ctx context.Context, id pgtype.UUID) (GetSprintWithWorkItemsRow, error)
	ListActiveSprints(ctx context.Context) ([]SprintManagementSprint, error)
	ListCompletedSprints(ctx context.Context, limit int32) ([]SprintManagementSprint, error)
	ListSoftDeletedSprints(ctx context.Context, arg ListSoftDeletedSprintsParams) ([]SprintManagementSprint, error)
	ListSprints(ctx context.Context, arg ListSprintsParams) ([]SprintManagementSprint, error)
	ListSprintsByStatus(ctx context.Context, arg ListSprintsByStatusParams) ([]SprintManagementSprint, error)
	MoveWorkItemsToBacklog(ctx context.Context, sprintID pgtype.UUID) error
	PermanentlyDeleteSprint(ctx context.Context, id pgtype.UUID) error
	RestoreSprint(ctx context.Context, id pgtype.UUID) error
	SoftDeleteSprint(ctx context.Context, arg SoftDeleteSprintParams) error
	UpdateSprint(ctx context.Context, arg UpdateSprintParams) (SprintManagementSprint, error)
	UpdateSprintMetrics(ctx context.Context, arg UpdateSprintMetricsParams) (SprintManagementSprint, error)
	UpdateSprintStatus(ctx context.Context, arg UpdateSprintStatusParams) (SprintManagementSprint, error)
}

var _ Querier = (*Queries)(nil)
