// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sprints.sql

package sprints

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSprintsByStatus = `-- name: CountSprintsByStatus :one
SELECT COUNT(*) FROM sprint_management.sprints
WHERE status = $1 AND deleted_at IS NULL
`

func (q *Queries) CountSprintsByStatus(ctx context.Context, status SprintManagementSprintStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countSprintsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSprint = `-- name: CreateSprint :one
INSERT INTO sprint_management.sprints (
    name,
    description,
    status,
    start_date,
    end_date,
    capacity_points,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by
`

type CreateSprintParams struct {
	Name           string                       `json:"name"`
	Description    *string                      `json:"description"`
	Status         SprintManagementSprintStatus `json:"status"`
	StartDate      pgtype.Date                  `json:"start_date"`
	EndDate        pgtype.Date                  `json:"end_date"`
	CapacityPoints *int32                       `json:"capacity_points"`
	CreatedBy      pgtype.UUID                  `json:"created_by"`
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (SprintManagementSprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.CapacityPoints,
		arg.CreatedBy,
	)
	var i SprintManagementSprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CapacityPoints,
		&i.CommittedPoints,
		&i.CompletedPoints,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getSprintByID = `-- name: GetSprintByID :one
SELECT id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.sprints
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSprintByID(ctx context.Context, id pgtype.UUID) (SprintManagementSprint, error) {
	row := q.db.QueryRow(ctx, getSprintByID, id)
	var i SprintManagementSprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CapacityPoints,
		&i.CommittedPoints,
		&i.CompletedPoints,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getSprintByIDIncludingDeleted = `-- name: GetSprintByIDIncludingDeleted :one
SELECT id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.sprints
WHERE id = $1
`

func (q *Queries) GetSprintByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (SprintManagementSprint, error) {
	row := q.db.QueryRow(ctx, getSprintByIDIncludingDeleted, id)
	var i SprintManagementSprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CapacityPoints,
		&i.CommittedPoints,
		&i.CompletedPoints,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getSprintWithWorkItems = `-- name: GetSprintWithWorkItems :one
SELECT
    s.id, s.name, s.description, s.status, s.start_date, s.end_date, s.capacity_points, s.committed_points, s.completed_points, s.created_by, s.created_at, s.updated_at, s.deleted_at, s.deleted_by,
    COUNT(wi.id) as work_item_count,
    COALESCE(SUM(wi.story_points), 0) as total_story_points,
    COALESCE(SUM(CASE WHEN wi.status = 'done' THEN wi.story_points ELSE 0 END), 0) as completed_story_points
FROM sprint_management.sprints s
LEFT JOIN sprint_management.work_items wi ON s.id = wi.sprint_id AND wi.deleted_at IS NULL
WHERE s.id = $1 AND s.deleted_at IS NULL
GROUP BY s.id
`

type GetSprintWithWorkItemsRow struct {
	ID                   pgtype.UUID                  `json:"id"`
	Name                 string                       `json:"name"`
	Description          *string                      `json:"description"`
	Status               SprintManagementSprintStatus `json:"status"`
	StartDate            pgtype.Date                  `json:"start_date"`
	EndDate              pgtype.Date                  `json:"end_date"`
	CapacityPoints       *int32                       `json:"capacity_points"`
	CommittedPoints      *int32                       `json:"committed_points"`
	CompletedPoints      *int32                       `json:"completed_points"`
	CreatedBy            pgtype.UUID                  `json:"created_by"`
	CreatedAt            pgtype.Timestamptz           `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz           `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz           `json:"deleted_at"`
	DeletedBy            pgtype.UUID                  `json:"deleted_by"`
	WorkItemCount        int64                        `json:"work_item_count"`
	TotalStoryPoints     interface{}                  `json:"total_story_points"`
	CompletedStoryPoints interface{}                  `json:"completed_story_points"`
}

func (q *Queries) GetSprintWithWorkItems(ctx context.Context, id pgtype.UUID) (GetSprintWithWorkItemsRow, error) {
	row := q.db.QueryRow(ctx, getSprintWithWorkItems, id)
	var i GetSprintWithWorkItemsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CapacityPoints,
		&i.CommittedPoints,
		&i.CompletedPoints,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.WorkItemCount,
		&i.TotalStoryPoints,
		&i.CompletedStoryPoints,
	)
	return i, err
}

const listActiveSprints = `-- name: ListActiveSprints :many
SELECT id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.sprints
WHERE status = 'active' AND deleted_at IS NULL
ORDER BY start_date DESC, id
`

func (q *Queries) ListActiveSprints(ctx context.Context) ([]SprintManagementSprint, error) {
	rows, err := q.db.Query(ctx, listActiveSprints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementSprint{}
	for rows.Next() {
		var i SprintManagementSprint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CapacityPoints,
			&i.CommittedPoints,
			&i.CompletedPoints,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedSprints = `-- name: ListCompletedSprints :many
SELECT id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.sprints
WHERE status = 'completed' AND deleted_at IS NULL
ORDER BY end_date DESC, id
LIMIT $1
`

func (q *Queries) ListCompletedSprints(ctx context.Context, limit int32) ([]SprintManagementSprint, error) {
	rows, err := q.db.Query(ctx, listCompletedSprints, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementSprint{}
	for rows.Next() {
		var i SprintManagementSprint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CapacityPoints,
			&i.CommittedPoints,
			&i.CompletedPoints,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoftDeletedSprints = `-- name: ListSoftDeletedSprints :many
SELECT id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.sprints
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id
LIMIT $1 OFFSET $2
`

type ListSoftDeletedSprintsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSoftDeletedSprints(ctx context.Context, arg ListSoftDeletedSprintsParams) ([]SprintManagementSprint, error) {
	rows, err := q.db.Query(ctx, listSoftDeletedSprints, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementSprint{}
	for rows.Next() {
		var i SprintManagementSprint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CapacityPoints,
			&i.CommittedPoints,
			&i.CompletedPoints,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprints = `-- name: ListSprints :many
SELECT id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.sprints
WHERE deleted_at IS NULL
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) > ($2::timestamptz, $3::uuid)
  )
  AND (
    $4::text IS NULL
    OR name ILIKE '%' || $4::text || '%'
    OR description ILIKE '%' || $4::text || '%'
  )
  AND (
    $5::text[] IS NULL
    OR status::text = ANY($5::text[])
  )
ORDER BY created_at ASC, id ASC
LIMIT $1
`

type ListSprintsParams struct {
	Limit           int32              `json:"limit"`
	CursorTimestamp pgtype.Timestamptz `json:"cursor_timestamp"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	SearchQuery     *string            `json:"search_query"`
	StatusFilter    []string           `json:"status_filter"`
}

func (q *Queries) ListSprints(ctx context.Context, arg ListSprintsParams) ([]SprintManagementSprint, error) {
	rows, err := q.db.Query(ctx, listSprints,
		arg.Limit,
		arg.CursorTimestamp,
		arg.CursorID,
		arg.SearchQuery,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementSprint{}
	for rows.Next() {
		var i SprintManagementSprint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CapacityPoints,
			&i.CommittedPoints,
			&i.CompletedPoints,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsByStatus = `-- name: ListSprintsByStatus :many
SELECT id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by FROM sprint_management.sprints
WHERE status = $1 AND deleted_at IS NULL
ORDER BY start_date DESC, id
LIMIT $2 OFFSET $3
`

type ListSprintsByStatusParams struct {
	Status SprintManagementSprintStatus `json:"status"`
	Limit  int32                        `json:"limit"`
	Offset int32                        `json:"offset"`
}

func (q *Queries) ListSprintsByStatus(ctx context.Context, arg ListSprintsByStatusParams) ([]SprintManagementSprint, error) {
	rows, err := q.db.Query(ctx, listSprintsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintManagementSprint{}
	for rows.Next() {
		var i SprintManagementSprint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CapacityPoints,
			&i.CommittedPoints,
			&i.CompletedPoints,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveWorkItemsToBacklog = `-- name: MoveWorkItemsToBacklog :exec
UPDATE sprint_management.work_items
SET sprint_id = NULL
WHERE sprint_id = $1 AND status != 'done' AND deleted_at IS NULL
`

func (q *Queries) MoveWorkItemsToBacklog(ctx context.Context, sprintID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, moveWorkItemsToBacklog, sprintID)
	return err
}

const permanentlyDeleteSprint = `-- name: PermanentlyDeleteSprint :exec
DELETE FROM sprint_management.sprints
WHERE id = $1
`

func (q *Queries) PermanentlyDeleteSprint(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, permanentlyDeleteSprint, id)
	return err
}

const restoreSprint = `-- name: RestoreSprint :exec
UPDATE sprint_management.sprints
SET
    deleted_at = NULL,
    deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreSprint(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreSprint, id)
	return err
}

const softDeleteSprint = `-- name: SoftDeleteSprint :exec
UPDATE sprint_management.sprints
SET
    deleted_at = NOW() AT TIME ZONE 'UTC',
    deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteSprintParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteSprint(ctx context.Context, arg SoftDeleteSprintParams) error {
	_, err := q.db.Exec(ctx, softDeleteSprint, arg.ID, arg.DeletedBy)
	return err
}

const updateSprint = `-- name: UpdateSprint :one
UPDATE sprint_management.sprints
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    status = COALESCE($4, status),
    start_date = COALESCE($5, start_date),
    end_date = COALESCE($6, end_date),
    capacity_points = COALESCE($7, capacity_points),
    committed_points = COALESCE($8, committed_points),
    completed_points = COALESCE($9, completed_points)
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by
`

type UpdateSprintParams struct {
	ID              pgtype.UUID                      `json:"id"`
	Name            *string                          `json:"name"`
	Description     *string                          `json:"description"`
	Status          NullSprintManagementSprintStatus `json:"status"`
	StartDate       pgtype.Date                      `json:"start_date"`
	EndDate         pgtype.Date                      `json:"end_date"`
	CapacityPoints  *int32                           `json:"capacity_points"`
	CommittedPoints *int32                           `json:"committed_points"`
	CompletedPoints *int32                           `json:"completed_points"`
}

func (q *Queries) UpdateSprint(ctx context.Context, arg UpdateSprintParams) (SprintManagementSprint, error) {
	row := q.db.QueryRow(ctx, updateSprint,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.CapacityPoints,
		arg.CommittedPoints,
		arg.CompletedPoints,
	)
	var i SprintManagementSprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CapacityPoints,
		&i.CommittedPoints,
		&i.CompletedPoints,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const updateSprintMetrics = `-- name: UpdateSprintMetrics :one
UPDATE sprint_management.sprints
SET
    committed_points = $2,
    completed_points = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by
`

type UpdateSprintMetricsParams struct {
	ID              pgtype.UUID `json:"id"`
	CommittedPoints *int32      `json:"committed_points"`
	CompletedPoints *int32      `json:"completed_points"`
}

func (q *Queries) UpdateSprintMetrics(ctx context.Context, arg UpdateSprintMetricsParams) (SprintManagementSprint, error) {
	row := q.db.QueryRow(ctx, updateSprintMetrics, arg.ID, arg.CommittedPoints, arg.CompletedPoints)
	var i SprintManagementSprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CapacityPoints,
		&i.CommittedPoints,
		&i.CompletedPoints,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const updateSprintStatus = `-- name: UpdateSprintStatus :one
UPDATE sprint_management.sprints
SET status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, status, start_date, end_date, capacity_points, committed_points, completed_points, created_by, created_at, updated_at, deleted_at, deleted_by
`

type UpdateSprintStatusParams struct {
	ID     pgtype.UUID                  `json:"id"`
	Status SprintManagementSprintStatus `json:"status"`
}

func (q *Queries) UpdateSprintStatus(ctx context.Context, arg UpdateSprintStatusParams) (SprintManagementSprint, error) {
	row := q.db.QueryRow(ctx, updateSprintStatus, arg.ID, arg.Status)
	var i SprintManagementSprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CapacityPoints,
		&i.CommittedPoints,
		&i.CompletedPoints,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
