#!/usr/bin/env python3
"""Merge DnD OpenAPI spec with auth endpoints into a combined spec."""

import yaml
from pathlib import Path

script_dir = Path(__file__).parent.absolute()

with open(script_dir / 'api/openapi/dnd.yaml', 'r') as f:
    dnd = yaml.safe_load(f)

with open(script_dir.parent / 'go_auth/api/openapi/auth.yaml', 'r') as f:
    auth = yaml.safe_load(f)

combined = {
    'openapi': '3.0.3',
    'info': {
        'title': 'DnD API with Authentication',
        'version': '1.0.0',
        'description': 'Complete DnD API including authentication endpoints',
    },
    'servers': [
        {'url': 'http://localhost:8004', 'description': 'Local development server'}
    ],
    'tags': auth.get('tags', []) + dnd.get('tags', []),
    'paths': {},
    'components': {
        'schemas': {},
        'responses': {},
        'securitySchemes': {},
    },
}

# Auth paths first, prefixed with /api/v1
for path, methods in auth.get('paths', {}).items():
    combined['paths']['/api/v1' + path] = methods

# DnD paths after
combined['paths'].update(dnd.get('paths', {}))

# Merge components
for spec in [dnd, auth]:
    if 'components' not in spec:
        continue
    for section in ('schemas', 'responses', 'securitySchemes'):
        if section in spec['components']:
            combined['components'][section].update(spec['components'][section])

combined['security'] = [{'BearerAuth': []}]

warning = """# ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
#
# This file is automatically generated by merge-openapi.py
# To make changes, edit the source files:
#   - api/openapi/dnd.yaml
#   - ../go_auth/api/openapi/auth.yaml
#
# Then regenerate by running:
#   python3 merge-openapi.py
#
# Any manual changes to this file will be overwritten!
#
"""

out = script_dir / 'api/openapi/combined-with-auth.yaml'
with open(out, 'w') as f:
    f.write(warning)
    yaml.dump(combined, f, default_flow_style=False, sort_keys=False)

print(f'✅ Generated: {out}')
print(f'📊 Total paths: {len(combined["paths"])}')
for path in sorted(combined['paths'].keys()):
    print(f'  - {path}')
